linkPrefix = "/protocol"
name = "@melonproject/protocol"
license = "GPL-3.0"
version = "0.4.0-live.2"
description = "Technology Regulated Investment Funds"
homepage = "https://github.com/melonproject/protocol#readme"
author = "“Melonport AG <“team@melonport.com”>"
buildTime = 2017-11-17T15:27:52.165Z
target = "scripts/doxity"
src = "$(find ./src -type f -name '*.sol' -not -name '*.t.sol' -not -name 'Governance.sol')"
dir = "pages/docs"
source = "https://github.com/DigixGlobal/doxity-gatsby-starter-project/archive/a4886b7a7a04c018ac04fed3125d7d4785e74bed.tar.gz"
out = "docs"

[interaction]